FROM php:7.2-fpm

RUN apt-get update && apt-get install -y procps vim
RUN curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/bin/composer
RUN apt-get install -y zlib1g-dev libzip-dev && docker-php-ext-install zip

EXPOSE 9000
CMD ["php-fpm"]