version: '3'
services:
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
  web:
    image: nginx:latest
    volumes:
      - ../source:/source
      - ./web/etc/nginx/conf.d/php72.test.conf:/etc/nginx/conf.d/php72.test.conf
      - ./web/etc/nginx/conf.d/php73.test.conf:/etc/nginx/conf.d/php73.test.conf
  php72:
    image: niceman114/php72:0.1
    build:
        context: .
        dockerfile: Dockerfile-php72
    volumes:
      - ../source:/source
  php73:
    image: niceman114/php73:0.1
    build:
      context: .
      dockerfile: Dockerfile-php73
    volumes:
      - ../source:/source